### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'out\txndb.json'

### ISSUE THREAD

**Issue by DannyDeLoach** [skhavari/cheddardog#13]
Hi. This is an extremely helpful script. Unfortunately, I keep getting the same error each time I run it.

I start the script with, 'npm run refresh'.
The script runs.
It opens up the browser and successfully logs in to my bank.
It navigates to the correct page and downloads the transactions.
Then, it ends with an error code.

Here is the output of the script:

> cheddardog@2.2.77 refresh D:\Google Drive\Finances\Automate transaction downloads\cheddardog_2
> node dist/src/refresh.js

Refresh configuration:
√ refresh configuration read.  Will refresh 1 accounts

Starting cheddardog v2.2.77:
√ browser launched
√ page created

Fetching BofA Transactions:
√ rm -rf C:\Users\danny\Downloads\stmt*.csv
√ https://www.bankofamerica.com loaded
√ username entered
√ password entered
√ signed in
√ account page loaded
√ download form opened
√ file type selected
√ custom date range 11/29/2019 to 01/29/2020 configured
√ download complete
√ statement loaded
√ loaded 51 transactions

❌ Error: ENOENT: no such file or directory, open 'out\txndb.json'
❌ Error: ENOENT: no such file or directory, open 'out\txndb.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Function.load (D:\Google Drive\Finances\Automate transaction downloads\cheddardog_2\dist\src\store\store.js:40:36)
    at Function.update (D:\Google Drive\Finances\Automate transaction downloads\cheddardog_2\dist\src\store\store.js:48:26)
    at D:\Google Drive\Finances\Automate transaction downloads\cheddardog_2\dist\src\refresh.js:19:19
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! cheddardog@2.2.77 refresh: `node dist/src/refresh.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the cheddardog@2.2.77 refresh script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\danny\AppData\Roaming\npm-cache\_logs\2020-01-29T13_45_05_191Z-debug.log
PS D:\Google Drive\Finances\Automate transaction downloads\cheddardog_2>

I've attached the log file:
[2020-01-29T13_45_05_191Z-debug.log](https://github.com/skhavari/cheddardog/files/4128359/2020-01-29T13_45_05_191Z-debug.log)

Thanks for any help you can provide in getting past this error.

**Comment by skhavari** [comment]
`echo "[]" > out/txndb.json` should do the trick
